<a href="https://colab.research.google.com/github/abdulwasaeee/Pytorch-Bootcamp/blob/main/pytorch-basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [64]:
torch.__version__

'2.8.0+cu126'

In [65]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [66]:
scalar.ndim

0

In [67]:
scalar.shape

torch.Size([])

In [68]:
scalar.item()

7

In [69]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [70]:
vector.ndim

1

In [71]:
vector.shape

torch.Size([2])

In [72]:
matrix=torch.tensor([[7,7],[4,4],[1,1]])
matrix

tensor([[7, 7],
        [4, 4],
        [1, 1]])

In [73]:
matrix.ndim

2

In [74]:
matrix.shape

torch.Size([3, 2])

In [75]:
tensor=torch.tensor([[[7,7],[4,4],[1,1]]])
tensor

tensor([[[7, 7],
         [4, 4],
         [1, 1]]])

In [76]:
tensor.ndim

3

In [77]:
tensor.shape

torch.Size([1, 3, 2])

In [78]:
torch.rand(224,224,3)

tensor([[[1.3319e-01, 9.3460e-01, 5.9358e-01],
         [8.6940e-01, 5.6772e-01, 7.4109e-01],
         [4.2940e-01, 8.8544e-01, 5.7390e-01],
         ...,
         [9.9791e-01, 7.5470e-01, 1.3641e-01],
         [8.8455e-01, 3.8850e-01, 3.9324e-01],
         [4.5545e-02, 4.2129e-01, 8.5366e-01]],

        [[5.6972e-01, 2.0877e-01, 6.5391e-01],
         [3.3968e-01, 9.5650e-01, 6.6023e-02],
         [3.4206e-01, 1.7213e-02, 3.0308e-01],
         ...,
         [5.3984e-01, 2.1868e-01, 2.7492e-01],
         [6.7008e-01, 6.1587e-02, 4.2213e-01],
         [4.8892e-01, 2.9742e-01, 6.8196e-01]],

        [[5.3223e-01, 8.5103e-01, 4.5559e-01],
         [1.8443e-01, 8.5328e-01, 5.6982e-01],
         [3.5680e-01, 1.7045e-01, 6.1719e-01],
         ...,
         [9.1501e-01, 2.6114e-01, 2.9279e-01],
         [5.4622e-01, 6.2962e-01, 4.5285e-01],
         [8.4301e-01, 2.0853e-01, 6.7919e-01]],

        ...,

        [[3.1047e-01, 9.3657e-01, 5.2111e-01],
         [7.5457e-01, 4.3883e-01, 1.7798e-01]

In [79]:
torch.zeros(2,2,2)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [80]:
torch.ones(2,2,2)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [81]:
torch.arange(1,11,2)

tensor([1, 3, 5, 7, 9])

In [82]:
tensor.dtype

torch.int64

In [83]:
torch.tensor([1.0,2.0,5.0]).dtype

torch.float32

In [84]:
a=torch.tensor([1.0,2.0,5.0])
b=torch.tensor([1.0,2.0,5.0],dtype=torch.float16)
(a*b).dtype

torch.float32

In [85]:
print(a.dtype,a.device,a.shape,a.ndim)

torch.float32 cpu torch.Size([3]) 1


In [86]:
a+10

tensor([11., 12., 15.])

In [87]:
a*10

tensor([10., 20., 50.])

In [88]:
a-1

tensor([0., 1., 4.])

In [89]:
a*b

tensor([ 1.,  4., 25.])

In [90]:
x=torch.tensor([[1,2,3],[1,2,3],[1,2,3]])
x*x

tensor([[1, 4, 9],
        [1, 4, 9],
        [1, 4, 9]])

In [91]:
torch.matmul(x,x)

tensor([[ 6, 12, 18],
        [ 6, 12, 18],
        [ 6, 12, 18]])

In [92]:
z=torch.tensor([[1,2,3],[4,5,6]])
z.shape

torch.Size([2, 3])

In [93]:
z.T.shape

torch.Size([3, 2])

In [94]:
z.dtype

torch.int64

In [95]:
z=z.type(torch.float32)

In [96]:
torch.min(z),torch.max(z),torch.sum(z),torch.mean(z)

(tensor(1.), tensor(6.), tensor(21.), tensor(3.5000))

In [97]:
z.min() , z.max(), z.sum(), z.mean()

(tensor(1.), tensor(6.), tensor(21.), tensor(3.5000))

In [98]:
z.argmin(), z.argmax()

(tensor(0), tensor(5))

In [99]:
c=torch.tensor([1,2,3,4,5,6,7,8,9])
c.shape

torch.Size([9])

In [100]:
c.reshape(3,3)


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [101]:
c.view(9,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [102]:
w=torch.tensor([1,2,3,4])
torch.stack([w,w,w],dim=1), torch.stack([w,w,w],dim=0)

(tensor([[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3],
         [4, 4, 4]]),
 tensor([[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]]))

In [103]:
b.reshape(1,3).shape

torch.Size([1, 3])

In [104]:
b.reshape(1,3).squeeze().shape

torch.Size([3])

In [105]:
b.shape

torch.Size([3])

In [106]:
b.unsqueeze(dim=0)

tensor([[1., 2., 5.]], dtype=torch.float16)

In [107]:
b.unsqueeze(dim=1)

tensor([[1.],
        [2.],
        [5.]], dtype=torch.float16)

In [108]:
r=torch.rand(2,3,5)
r

tensor([[[0.1167, 0.1133, 0.8600, 0.2933, 0.5889],
         [0.4117, 0.0992, 0.3078, 0.7786, 0.8016],
         [0.3649, 0.6286, 0.9663, 0.7687, 0.4566]],

        [[0.5745, 0.9200, 0.3230, 0.8613, 0.0919],
         [0.3102, 0.9536, 0.6002, 0.0351, 0.6826],
         [0.3743, 0.5220, 0.1336, 0.9666, 0.9754]]])

In [109]:
r.shape

torch.Size([2, 3, 5])

In [110]:
torch.permute(r,(2,1,0)).shape

torch.Size([5, 3, 2])

In [111]:
b

tensor([1., 2., 5.], dtype=torch.float16)

In [112]:
npb=torch.Tensor.numpy(b)
npb

array([1., 2., 5.], dtype=float16)

In [124]:
g=torch.from_numpy(npb)
g

tensor([1., 2., 5.], dtype=torch.float16)

In [125]:
g.numpy()

array([1., 2., 5.], dtype=float16)

In [114]:
torch.manual_seed(42)
torch.rand(3,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

In [115]:
#after assigning a GPU
!nvidia-smi

Mon Sep  8 02:56:57 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   76C    P0             34W /   70W |     104MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [116]:
torch.cuda.is_available()

True

In [117]:
torch.cuda.device_count()

1

In [130]:
device= "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [119]:
z.device

device(type='cpu')

In [120]:
z=z.to(device)
z.device

device(type='cuda', index=0)

In [133]:
x.cpu().device

device(type='cpu')

In [134]:
z.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [135]:
z.cpu().numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [136]:
z.to('cpu').numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)